### PR TITLE
Add support for previews

### PR DESCRIPTION
**Pull request by vilpersson**
Returns languages and translations when querying  post previews.

### CODE REVIEW

**Comment by esamattis** [comment]
Merged master here and added tests.

For some reason the `testCanHaveLanguageField` passed even without your changes. 

https://github.com/valu-digital/wp-graphql-polylang/blob/bebf17a1c4a253498e84bd00584db7a6ee4aa810/tests/wpunit/PostPreviewQueryTest.php#L25-L59

Can you eleborate when it failed before?

**Comment by esamattis** [comment]
Oh wait. Now it fails in the CI 🤔

**Comment by vilpersson** [comment]
Are you sure that Polylang is setting the language of the preview post? 

After creating preview, the newly created revision does not seem get the term relationship to the `language` taxomony, and this query will return `null`

```
query PREVIEW_QUERY {
    page(id: 7844, idType: DATABASE_ID, asPreview: true) {
        language {
            slug
        }
    }
}
```

If you go and check the post id of the revision, and set the language via `pll_set_post_language` function, then the you'll get correct language.

**Comment by esamattis** [comment]
It explicitly set here in the test:

https://github.com/valu-digital/wp-graphql-polylang/pull/30/files#diff-c9b04d9613c130bcf51b35ed35bf1490R42

But I'll test this in a real WP env. Unit testing Polylang correctly is actually quite hard since it's initialization so tied to the normal WP boot up.

**Comment by esamattis** [comment]
Ah. It seems that in a real WP instance the language of preview is not set at all so we need to fallback to the language of the original post.

**Comment by esamattis** [comment]
Merged, thank you!

Made couple additional fixes to this:

Must remove the original parent from the `translations` list to avoid duplicate entries
https://github.com/valu-digital/wp-graphql-polylang/commit/659d1011c704fb19f61c6c6c24f80c7c0eca9a3d

Also needed to use the parent id for the `name` and `locale` fields too
https://github.com/valu-digital/wp-graphql-polylang/commit/c521f30fb2d852987ed28f6ccbf1fc76d6a0b741

**Comment by esamattis** [comment]
Released in v0.5.0 
https://github.com/valu-digital/wp-graphql-polylang/compare/v0.4.0...v0.5.0

**Comment by vilpersson** [comment]
@esamattis Great, thank you!

**Pull request merged**
