### PR TITLE
Feature/multi languages

### PR DESCRIPTION
**Pull request by simptheshrimp**
- Adds `languages` where arg to extend functionality to filter for multiple languages at the time

### CODE REVIEW

**Comment by esamattis** [comment]
Thank you! Looks good 👌  Composer is not happy for some reason in the GH action but will look into it soon.

**Comment by michaellopez** [comment]
@esamattis The message is:

```
ivome/graphql-relay-php v0.3.1 requires php >=5.4,<8.0-DEV -> your php version (8.0.5) does not satisfy that requirement.
```

Basically the image is using PHP v8.0.5. The image `ubuntu-latest` [used in the action](https://github.com/valu-digital/wp-graphql-polylang/blob/master/.github/workflows/test.yml#L15) has both PHP v7.4.18 and v8.0.5. See [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#php) So I'm guessing that the binary `php` points to `8.0.5` and there is something like `php74` that points to `7.4.18`. I think that the action needs to run `composer` with `php74` (or whatever the binary is named) https://github.com/valu-digital/wp-graphql-polylang/blob/master/.github/run-tests#L10

**Comment by esamattis** [comment]
Merged in https://github.com/valu-digital/wp-graphql-polylang/pull/50

**Comment by esamattis** [comment]
I also added a test for the `languages` where arg this pr actually adds 😅

**Comment by esamattis** [comment]
Released in v0.6.0! https://github.com/valu-digital/wp-graphql-polylang/releases/tag/v0.6.0

**Pull request closed without merging**
